# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Personal startup apps
exec-once = blueman-applet
exec-once = qs
exec-once = $HOME/.config/hypr/scripts/KeybindsLayoutInit.sh
