# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Commands and Apps to be executed at launch

# Workspace 1: kitty and tmux
#exec-once = kitty --class kitty -e tmux
#exec-once = kitty --class kitty
#exec-once = sleep 1 && hyprctl dispatch movetoworkspacesilent 1,class:kitty
#
## Workspace 2: chromium-browser
#exec-once = chromium-browser
#exec-once = sleep 1 && hyprctl dispatch movetoworkspacesilent 2,class:chromium-browser
#
## Workspace 3: whatsie, Telegram, Signal
#exec-once = whatsie
#exec-once = telegram-desktop
#exec-once = signal-desktop
#exec-once = sleep 2 && hyprctl dispatch movetoworkspacesilent 3,class:com.ktechpit.whatsie
#exec-once = sleep 2 && hyprctl dispatch movetoworkspacesilent 3,class:org.telegram.desktop
#exec-once = sleep 2 && hyprctl dispatch movetoworkspacesilent 3,class:signal
#
