[tools]
claude = "latest"
codex = "latest"
gh = "latest"
"llama.cpp" = { version = "latest", version_prefix = "b" }
node = "latest"
ollama = "latest"
opencode = "latest"
pi = "latest"
ruby = "latest"
